---
services:
  bmd-dataspace-api:
    image: "registry.gitlab.com/naturalis/bii/bmd/bmd-dataspace-api:${IMAGE_VERSION:?Missing IMAGE_VERSION}"
    container_name: bmd-dataspace-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - "${DATA_DIR:?Missing DATA_DIR}:/data/bmd"
      - "./logback-spring.xml:/logback-spring.xml"
    environment:
      JAVA_TOOL_OPTIONS: "${JAVA_TOOL_OPTIONS:?Missing JAVA_TOOL_OPTIONS}"
    env_file:
      - .env
