---
all:
  hosts:
    prod:
      ansible_host: prd-bmd-dataspace.hosts.naturalis.io
      ansible_user: development

    dev:
      ansible_host: dev-bmd-dataspace.hosts.naturalis.io
      ansible_user: development

    vagrant: # future use
      ansible_host: 127.0.0.1
      ansible_port: 2222
      ansible_user: vagrant
      ansible_private_key_file: .vagrant/machines/vagrant1/virtualbox/private_key

  children:
    # We have a special "aws" group because AWS credentials are created through
    # pipelines managed by infra and placed in a separate corner of HC Vault
    # (/tenant/letsencrypt). pull-vault-secrets.sh will read the letsencrypt
    # secret and save it as aws.json under ansible/inventory/group_vars/aws.json
    # The aws group ensures that Ansible will pick up aws.json and expose its
    # contents as variables.
    aws:
      hosts:
        prod:
        dev:
