---
- name: Preflight checks
  ansible.builtin.import_tasks: preflight.yml

- name: Check directories
  ansible.builtin.import_tasks: mkdir.yml

- name: Push files
  ansible.builtin.import_tasks: push-files.yml

- name: Render and push .env
  ansible.builtin.import_tasks: env.yml

- name: Restart container
  ansible.builtin.import_tasks: restart-container.yml
