#!/bin/bash

if [ -z "${BASE_DIR:-}" ]; then
  echo "o ---> ERROR: functions.sh requires BASE_DIR to be set" >&2
  exit 1
fi

# Constants:

ANSIBLE_DOCKER_IMAGE="registry.gitlab.com/naturalis/lib/ansible/docker-ansible:latest"

ANSIBLE_DIR="${BASE_DIR}/ansible"

HOSTS_FILE="${ANSIBLE_DIR}/inventory/hosts.yml"

# File containing HC Vault token. Generated by get-vault-token.sh. Read by
# pull-vault-secrets.sh
TOKEN_FILE="${ANSIBLE_DIR}/.vault-token"

# File containing Docker image tag. Generated by set-image-version.sh. Read by
# playbook.sh
VERSION_FILE="${ANSIBLE_DIR}/.image-version"

# File containing the output of `ansible-inventory --list`. This file is written
# inside an Ansible Docker container to /gateway, and picked up afterwards from
# ${ANSIBLE_DIR} (with ${ANSIBLE_DIR} being mapped to /gateway).
INVENTORY_FILE=".inventory.json"


trim() {
  local value="${1:?trim(): missing argument}"
  # Trim leading whitespace
  value="${value#"${value%%[![:space:]]*}"}"
  # Trim trailing whitespace
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "${value}"
}

# Prints a space-separated list of all groups within hosts.yml file that contain
# the specified host (either directly or indirectly). The implicit "all" and
# "ungrouped" groups are excluded from the list. The printed groups are used to
# look up identically named secrets in HC Vault.
get_ansible_groups() { # hostname
  local hostname="${1:?get_ansible_groups(): missing argument}"
  if ! is_valid_host "${hostname}"; then
    echo "o ---> No such host: ${hostname}" >&2
    return 1
  fi
  list_ansible_groups;
  local groups
  groups="$(filter_ansible_groups "${hostname}")"
  [ -n "$groups" ] && printf '%s\n' "$groups"
  return 0
}

# Calls `ansible-inventory --list` and writes the output to ${ANSIBLE_DIR}/${INVENTORY_FILE}.
list_ansible_groups() {
  docker run --rm \
    -v "${ANSIBLE_DIR}/:/gateway/" \
    -v "${HOSTS_FILE}:/hosts.yml:ro" \
    -e ANSIBLE_CONFIG="/gateway/ansible.cfg" \
    -t \
    "${ANSIBLE_DOCKER_IMAGE}" \
    sh -lc "ansible-inventory -i '/hosts.yml' --list > '/gateway/${INVENTORY_FILE}'"
}

# Reads ${ANSIBLE_DIR}/${INVENTORY_FILE} and applies a jq filter that selects only
# those Ansible groups that contain the specified host. The jq filter is placed in
# a separate file (ansible/inventory.jq).
filter_ansible_groups() { # hostname
  local hostname="$1"
  jq --raw-output \
   --arg hostname "$hostname" \
   --from-file "${ANSIBLE_DIR}/inventory.jq" \
   "${ANSIBLE_DIR}/${INVENTORY_FILE}"
}

# Determines whether the provided argument occurs at least once as a host in
# inventory/hosts.yml.
is_valid_host() { # hostname
  local hostname="$1"
  if docker run --rm \
    -v "${ANSIBLE_DIR}/ansible.cfg:/ansible.cfg:ro" \
    -v "${HOSTS_FILE}:/hosts.yml:ro" \
    -e ANSIBLE_CONFIG="/ansible.cfg" \
    -t \
    "${ANSIBLE_DOCKER_IMAGE}" \
    ansible-inventory -i "/hosts.yml" --host "${hostname}" >/dev/null; then
    return 0
  else
    return 1
  fi
}

# Retrieves a secret from HC Vault and saves it locally. The file will only be written
# if the endpoint is valid (the secret exists - no 404) and if the returned JSON is
# not empty (at least one key-value pair). However, the function does _not_ fail if
# either is not the case. It is up to the caller to decide how to handle absent/empty
# secrets.
get_secret_as_json() { # secret_name, output_file

  # Root of our little corner in HC Vault
  local hc_vault_base="${VAULT_SERVER_URL}/v1/kv2/data/${VAULT_PATH}"

  # HC Vault Path to secret relative to hc_vault_base
  local secret="${1:?No secret specified}"
  # File system path relative to ${BASE_DIR}
  local save_as="${2:?No output file specified}"
  local endpoint="${hc_vault_base}/${secret}"
  local token="$(<"${TOKEN_FILE}")"

  echo "o ---> Retrieving secret \"${secret}\""

  # Get response body __and__ HTTP status code in one CURL request
  # by appending (-w) the HTTP status code to response body
  local body="$(curl -sS -w $'\n%{http_code}' -H "X-Vault-Token: ${token}" "${endpoint}")" || true
  # extracting the status from the response body
  local status="${body##*$'\n'}"
  # and then shaving off the status from body again
  body="${body%$'\n'*}"

  if [[ $status -eq 200 ]]; then
    # Only write a file if there are keys under .data.data
    if jq -e '.data.data | length > 0' >/dev/null 2>&1 <<< "$body"; then
      jq '.data.data' <<< "$body" > "${save_as}"
      echo "o ---> Secret saved"
    else
      echo "o ---> Empty secret"
    fi
  elif [[ $status -eq 404 ]]; then
    echo "o ---> No secret there"
  else
    echo "$body" >&2 # E.g. "403 Permission Denied"
    echo >&2
    exit 1
  fi

}

# Ensures HC vault CLI is available. If not, installs it silently in the .tools
# directory (git-ignored) of this repo.
#
# You can use Hashicorp's Docker image to retrieve secrets. In theory you can also use
# it to get a vault token, but in practice it's almost impossible. When your vault
# token is expired, the CLI will automatically open a browser tab, allowing you to
# request a new token. Since this processed is supervised by Azure AD, the token is
# always granted immediately (unless you need it sign in to Azure AD itself again). So
# while vault token retrieval is not strictly speaking a headless process, in practice
# it almost always is. (You may just notice a new tab in your browser once
# get-vault-token.sh completes.) When running the CLI from within a Docker container,
# all this becomes much more problematic.
ensure_vault_cli() {
  if command -v vault > /dev/null 2>&1; then # already installed by user
    return 0
  fi
  : "${VAULT_CLI_DOWNLOAD_URL:?Missing value for VAULT_CLI_DOWNLOAD_URL}"
  vault_dir="${BASE_DIR}/.tools/vault"
  if [ -d "$vault_dir" ]; then # already installed by ensure_vault_cli
    PATH="${vault_dir}:$PATH"
    export PATH
    return 0
  fi
  mkdir -p "$vault_dir"
  # From here onward, if anything goes wrong, delete $vault_dir again, so
  # next time we will at least try again.
  trap 'rc=$?; if [ $rc -ne 0 ]; then rm -rf "$vault_dir"; fi; exit $rc' 0 INT TERM HUP
  echo "o ---> Bootstrapping HC Vault CLI from $vault_dir"
  url="$VAULT_CLI_DOWNLOAD_URL"
  zip_name="${url##*/}"
  zip_path="${vault_dir}/${zip_name}"
  vault_bin="${vault_dir}/vault"
  curl -fsSL -o "$zip_path" "$url"
  (cd "$vault_dir" && unzip -o "$zip_name" > /dev/null)
  chmod +x "$vault_bin"
  PATH="${vault_dir}:$PATH"
  export PATH
  # On success, disable trap (we don't want $vault_dir to disappear if user
  # exits terminal or does a Control-C)
  trap - 0 INT TERM HUP
}

# Ensures jq is available. If not, installs it silently in the .tools directory
# (git-ignored) of this repo.
ensure_jq() {
  if command -v jq > /dev/null 2>&1; then # already installed
    return 0
  fi
  : "${JQ_DOWNLOAD_URL:?Missing value for JQ_DOWNLOAD_URL}"
  jq_dir="${BASE_DIR}/.tools/jq"
  if [ -d "$jq_dir" ]; then # already installed by ensure_jq
    PATH="${jq_dir}:$PATH"
    export PATH
    return 0
  fi
  mkdir -p "$jq_dir"
  trap 'rc=$?; if [ $rc -ne 0 ]; then rm -rf "$jq_dir"; fi; exit $rc' 0 INT TERM HUP
  echo "o ---> Bootstrapping jq from $jq_dir"
  url="$JQ_DOWNLOAD_URL"
  dl_name="${url##*/}"
  dl_path="${jq_dir}/${dl_name}"
  jq_bin="${jq_dir}/jq"
  curl -fsSL -o "$dl_path" "$url"
  chmod +x "$dl_path"
  mv "$dl_path" "$jq_bin"
  PATH="${jq_dir}:$PATH"
  export PATH
  trap - 0 INT TERM HUP
}

