---
# Identity knob
compose_project_name: "bmd-dataspace-api"

# Derived locations (override if needed)
deploy_dir: "/opt/projects/{{ compose_project_name }}"
data_dir: "/data/bmd"

# Repo root relative to playbook_dir. playbook_dir is a magic variable
# that points to the directory from which the playbook is run. In our
# case, playbook.sh (which executes the ansible-playbook command) is
# located in the ansible directory.
repo_root: "{{ playbook_dir }}/.."

# Lists all files, relative to the repository's root directory, that
# must be pushed to the remote host
deployed_files:
  - "docker-compose.yml"
  - "docker-compose.traefik.yml"
  - "logback-spring.xml"

# Lists all shell scripts and other executables that must be pushed
deployed_executables:
  - "docker-blowtorch.sh"

